### ISSUE TITLE
fix Uncaught TypeError: Cannot read property 'removeChild' of null (#512 #487)

### ISSUE THREAD

**Issue by otsquest101** [cleandersonlobo/sweetalert2#2]
I am getting this issue , this is related to the wrapper you are using ...They have fixed it in their release..https://github.com/limonte/sweetalert2/releases/tag/v6.6.1 would you mind updating yours

**Comment by cleandersonlobo** [comment]
OK! Updated to the most recent release (v6.6.9)
;)

**Comment by otsquest101** [comment]
thanks so much for that : )
